server:
  port: 8091

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

broker:
  exchange: com.rodtech.javapocprojects.topic.exchange
  queue:
    transaction: com.rodtech.javapocprojects.topic.transaction
    transaction-credit-card: com.rodtech.javapocprojects.topic.transaction.credit-card
    transaction-bank: com.rodtech.javapocprojects.topic.transaction.bank
